name: Update README with Issue List
on:
  issues:
    types:
      - opened
      - edited

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README
        run: python update_readme.py

      - name: Set Git Config
        run: |
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.USEREMAIL }}"

      - name: Commit and Push Changes
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            git add README.md
            git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/niwanowa/niwanowa-ideas.git
            git commit -m "Update README with latest issues"
            git push